### ISSUE TITLE
알고리즘 - 기초 블록들 추가하기

### ISSUE THREAD

**Issue by alirz-pixel** [2021community/Algorithm-skills#16]
### **이런걸 할겁니다.**
ex) '알고리즘'/'기초' 에 블록들을 추가할겁니다.

### **상세한 작업리스트**
- [x] 정렬
  - [x] 선택정렬
  - [x] 버블정렬
  - [x] 병합정렬
  - [x] 퀵정렬
- [x] 탐색
  - [x] 리니어
  - [x] 이분
  - [x] 두 포인터
  - [x] 해싱
- [x] DP

### **기타**

**Comment by Zzangeun** [comment]
정렬(퀵), 탐색(리니어, 이분) 그리디, dfs, bfs 추가해주세용
