### ISSUE TITLE
Share menu 수정

### ISSUE THREAD

**Issue by yeahhhhj** [2021community/Algorithm-skills#2]
### **이런걸 할 겁니다.**
share menu를 수정할 것입니다.

### **상세한 작업리스트**
- [x] Copy, Facebook, Twitter, Email 남기기
- [x] 나머지 삭제

### **기타**
![image](https://user-images.githubusercontent.com/50025713/131149609-2a6125dd-c313-45f5-a5fd-54ea642dfff7.png)

**Comment by JihyeKim0923** [comment]
![image](https://user-images.githubusercontent.com/48914876/130625118-89341623-eb56-458e-9fde-c2a480ae8149.png)

**Comment by Zzangeun** [comment]
위 그림에서 두번째 아이콘인 공유 버튼만 수정하셔야 됩니다.
