### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by Zzangeun** [2021community/Algorithm-skills#47]
### **이런걸 할 겁니다.**
README.md 파일을 우리의 프로젝트에 맞게 수정할겁니다.

### **상세한 작업리스트**
- [x] 제목
- [x] 대분류
- [x] 소분류
    - [x] 프로그래밍 언어
    - [x] 자료구조
    - [x] 알고리즘
    - [x] 코딩 테스트
- [x] 데모
- [x] FAQ
- [x] 목차
- [x] contributor

### **기타**

**Comment by alirz-pixel** [comment]
제가 리드미, 블루프린트의 제목과 대분류 수정하겠습니다!

**Comment by alirz-pixel** [comment]
README와 blueprint의 소분류 - 알고리즘을 수정하겠습니다!

**Comment by yeahhhhj** [comment]
저는 README와 blueprint의 소분류 - 자료구조와 contributors 수정하겠습니당 🎈

**Comment by JihyeKim0923** [comment]
저는 README의 소분류 - 코딩테스트와  Table of Contents를 수정하겠습니다.

**Comment by Zzangeun** [comment]
알고리즘 심화랑 이것만은 꼭 부분은 제가 하겠습니다.

**Comment by yeahhhhj** [comment]
License는 삭제하겠습니당~~😶💗
