### ISSUE TITLE
Description 배경 색상 수정

### ISSUE THREAD

**Issue by yeahhhhj** [2021community/Algorithm-skills#83]
### **어떤 버그인가요?**
description 배경 색이 투명으로 변경되었습니다.

### **어떻게 버그가 발견됐나요?**
1. 메인페이지에서
2. 블록의 description의
3. 배경색이 검정색 -> 투명색으로 변경되어 글이 보이지 않습니다.

### **이렇게 해결해주세요.**
배경색을 다시 검정색으로 변경해주세요.

### **참고 스크린샷**
![image](https://user-images.githubusercontent.com/50025713/132127976-e3450b62-91aa-453d-8983-6f5f37a1aa2e.png)

**Comment by alirz-pixel** [comment]
해결된 이슈라 닫겠습니다!
